### ISSUE TITLE
Invalid registry value and registry key enumeration

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/chocolatey#15]
> There is a problem, this (and other) plugin(s) enumerates the uninstall keys if there is an invalid entry. 

> On my computer I had to remove the invalid key NoModify in
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-base-8.1.0.0.201510222201 and recreated it as a valid DWORD with value 1. From then on the problem was gone.

> The entry was an invalid DWORD. AFAIK it was written with the wrong length information (8 instead of 4 bytes)

> My System runs Windows 10.

> Luckily I indeed exported the relevant registry entry before deleting and recreating it (with value 1):

```
--<snip>---
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-base-8.1.0.0.201510222201]
"NoModify"=hex(4):01,00,00,00,00,00,00,00
--</snip>---
```

Link: https://disqus.com/home/discussion/chocolatey/chocolatey_gallery_wkhtmltopdf_099/#comment-2679706558

**Comment by majkinetor** [comment]
I confirm this behavior. 

Here is the regedit screenshot

![image](https://cloud.githubusercontent.com/assets/85767/17324903/1bfe5038-58a9-11e6-90a3-fdef3befeda1.png)

After the import:

```
PS> [array]$key = Get-ItemProperty @($machine_key6432, $machine_key, $local_key) | ? { $_.DisplayName }
Get-ItemProperty : Specified cast is not valid.
At line:1 char:15
+ ... rray]$key = Get-ItemProperty @($machine_key6432, $machine_key, $local ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ItemProperty], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,Microsoft.PowerShell.Commands.GetItemPropertyCommand
```

**Comment by majkinetor** [comment]
Now, this is not a bug because `Get-ItemProperty` fails, which is Powershell function. It doesn't expect such value. I can probably work around it and display a warning. Seems like it happens to some number of people.

**Comment by majkinetor** [comment]
https://github.com/chocolatey/choco/issues/739

**Comment by majkinetor** [comment]
Ok, i classify it as a bug since there is a workaround and I should use https://chocolatey.org/docs/helpers-get-uninstall-registry-key.

**Comment by 2chg** [comment]
> I am also not sure how is this actually allowed to pass into registry ?! Might be an registry bug...
> (Comment on Bug #15)

For netbeans the culrpit is found in a programming error:
[Bug 251538 - Your Installer is Creating Invalid Data for the NoModify DWORD Key […]](https://netbeans.org/bugzilla/show_bug.cgi?id=251538#c2)
