### ISSUE TITLE
yed should not use $env:chocolatey_bin_root

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/chocolatey#7]
> @majkinetor $env:chocolatey_bin_root was not official and is deprecated for $env:ChocolateyBinRoot, both of which are adjusted to $env:ChocolateyToolsRoot in 0.9.10. You should only ever rely on it by using Get-BinRoot
> 
> Rob Reynolds @ferventcoder Jun 04 17:11
> @majkinetor aliases are not working in autodoc - but this is now the name for Get-BinRoot (calling the old still works) - https://chocolatey.org/docs/helpers-get-tools-location
> @majkinetor so no, you can never rely on the environment variable directly - always use Get-BinRoot

> Rob Reynolds @ferventcoder 15:07
> @majkinetor check for $env:ChocolateyBinRoot - see what it is set to. It sounds like something weird is going on in your environment - the 0.9.9 series would not allow just c:\

**Comment by majkinetor** [comment]
`$env:ChocolateyToolsRoot` is set to `c:\tools` here so it doesn't help. 

I finished by hardcoding `bin` part:

```$cmdPath     = join-path $env:ChocolateyInstall bin\yed.cmd```

**Comment by majkinetor** [comment]
This is the method used in installer: https://chocolatey.org/install.ps1

```
Write-Output 'Ensuring chocolatey commands are on the path'
$chocInstallVariableName = "ChocolateyInstall"
$chocoPath = [Environment]::GetEnvironmentVariable($chocInstallVariableName)
if ($chocoPath -eq $null -or $chocoPath -eq '') {
  $chocoPath = 'C:\ProgramData\Chocolatey'
}

$chocoExePath = Join-Path $chocoPath 'bin'
```

**Comment by ferventcoder** [comment]
> `$cmdPath = join-path $env:ChocolateyInstall 'bin\yed.cmd'`

This is correct - when the path you are looking for is the Chocolatey Install bin folder, it is not the binroot var. You do just as you have done above 👍
