### ISSUE TITLE
pandoc isn't added to PATH

### ISSUE THREAD

**Issue by Mailaender** [majkinetor/chocolatey#8]
`Adding pandoc to the PATH if needed` seems a bit misleading as `pandoc` or `pandoc.exe` isn't added to PATH at all. https://github.com/OpenRA/OpenRA/pull/11421

**Comment by majkinetor** [comment]
That can happen only if it doesn't detect install location since:

```
if ($installLocation) {
    Write-Host "Adding $packageName to the PATH if needed"
    Install-ChocolateyPath $installLocation "Machine"
}
```

Since it wrote the message it should be added. I have pandoc in number of systems and the PATH works.

The only recent change was  `ALLUSERS=1` setting which means it installs to program files.

**Comment by GraionDilach** [comment]
Actually, both of you are right. http://help.appveyor.com/discussions/questions/754-updating-path-to-find-program-installed-with-cinst#comment_35432560

**Comment by majkinetor** [comment]
Actually, no, only I am right :), that information is outdated

https://github.com/chocolatey/chocolatey/blob/master/src/helpers/functions/Install-ChocolateyPath.ps1#L35-L37

**Comment by GraionDilach** [comment]
Those lines are from 2012 according to Git blame (the whole file was last updated in Jan 2014) while the information I linked is from Dec 2014. I don't think the linked info is the one being outdated. :D

**Comment by majkinetor** [comment]
Those lines are currently on my system with latest choco.

Also, I use choco everyday, I know that this stuff works :dart: 

Anyway, I am ready to help if you find the way how.

**Comment by GraionDilach** [comment]
Well, I don't think this is a pandoc issue, it's just the way how choco works on AppVeyor.

**Comment by majkinetor** [comment]
It might be a pandoc package issue. Adding to path is not pandoc installer feature, its a package feature.

Choco should work on AppVeyor the same as everywhere else.
